### PR TITLE
Extract new strings (2023-11-17)

### PR DESCRIPTION
**Pull request by mozilla-pontoon**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by Delphine** [comment]
Had a chat with iOS team yesterday, they need to update strings here and cancel the removals.

**Comment by thatswinnie** [comment]
@Delphine @lmarceau and I solved it 😆 : the strings for the ids `Shopping.InfoCard.ReportSubmittedByCurrentUser.Description.v121` and `Shopping.InfoCard.ReportSubmittedByCurrentUser.Title.v121` are removed and later in the same file added again.
Could you please pull the strings again to get the missing strings from our repo?

**Comment by Delphine** [comment]
@thatswinnie Actually I see that these strings did change files, which is the reason it invalidates translations for these strings. They now live under `<file original="Shared/Supporting Files/en.lproj/Shopping.strings"`
You can tell that moving strings to another file will invalidate existing translations (see the "fr" xliff strings: they were translated when the strings were in the previous file, and now they are only in English).

Is there a reason we are moving both these strings to a different file?

**Comment by Delphine** [comment]
Actually I have a workaround for this so I might be able to fix this on my side 🙂

**Review by Delphine — APPROVED** [review]

**Pull request merged**
