### PR TITLE
iOS v29 - 20200916 1623 

### PR DESCRIPTION
**Pull request by nbhasin2**

### CODE REVIEW

**Review by Delphine — CHANGES_REQUESTED** [review]
Sorry, unfortunately this isn't going to work: changing file names deletes all existing translations within that file (look at the "fr" file for example).
We'd basically be losing everything we have :/

**Comment by nbhasin2** [comment]
> Sorry, unfortunately this isn't going to work: changing file names deletes all existing translations within that file (look at the "fr" file for example).
> We'd basically be losing everything we have :/

Yeah I saw 😞 how would you feel if I add same strings in a different file. Would that still require translation? They'll all be same strings.

Trying to brainstorm some ideas.

**Comment by Delphine** [comment]
Hmmm would you have an example please? Wanna make sure I'm on the same page : )

**Comment by flodolo** [comment]
The script you're using to populate the localized files can be temporarily hacked to map old strings to new strings.
https://github.com/mozilla-mobile/ios-l10n-scripts/blob/master/update-xliff.py

What the script does is:
1. Read the en-US XML file in `reference_tree`.
2. [Store existing translations](https://github.com/mozilla-mobile/ios-l10n-scripts/blob/master/update-xliff.py#L125) in a dictionary. The key of each element is `file:id:hash` (let's call it *migration_id*). File is the `original` attribute of the `file` element, `id` is the `id` attribute of the `trans-unit` element, `hash` is an hash of the actual English string. The latter is used to invalidate translations if the source string changed.
3. It starts walking `reference_tree`, and inject translations is there's a matching *migration_id*.

Now, it's clear why you lose translations if the `file` changes. The localized file won't have a translation with the matching *migration_id* when reaching the point 3 above.

What you can do, when you store the translations, is create mappings in that dictionary. For example, change the file name from `Client/ClearHistoryConfirm.strings` to `ClearHistoryConfirm.strings`, etc.

This will keep translations in the XLIFF file, but it still comes with downsides:
- The translation will lose attribution in Pontoon, since it will be a brand new string imported from the repository (but already translated).
- The string will lose history in Pontoon. That includes rejected translations, but also pending suggestions.

And with all that said, I strongly encourage the iOS team to figure out how the current toolchain works (we had a meeting a couple of months ago, but not sure what the action items from it were). Just by looking at that script, it's clear that it needs attention. And I'm saying that as someone who contributed most of the code for this file in early 2015.

**Comment by nbhasin2** [comment]
Hi @flodolo, thanks for pointing me to l10n scripts. I synced with Stefan and made changes to localization script. Hoping that next build would have proper changes. 

Once things are more stable plan is to cleanup old script.

**Pull request closed without merging**
