### PR TITLE
Test - Do Not Merge - Bug 1391631 - Remove test targets from XLIFF exports

### PR DESCRIPTION
**Pull request by st3fan**
Test PR to see if my script changes are working.

@flodolo @Delphine I made some changes to the scripts to ignore Test targets. There is no point in exporting those. All `*Tests/Info.plist` files should disappear.

(Ignore the string changes - i am running this on master, which is a bit ahead of the last export)

### CODE REVIEW

**Comment by st3fan** [comment]
Looks like they are still in `en-US` and `templates`. Maybe this needs to become a post-process-export step.

**Comment by flodolo** [comment]
Any reason for the weird version numbers (8.0, 1.0)?

Per IRC discussion, I need @mathjazz to confirm, but I think we can get rid of the templates folder, because it was only needed by Pootle.

**Comment by flodolo** [comment]
Side question: can you point me to the script? Are you talking about the update script, not the extraction, right?

**Comment by mathjazz** [comment]
> Per IRC discussion, I need @mathjazz to confirm, but I think we can get rid of the templates folder, because it was only needed by Pootle.

Actually Pontoon detects source folders in the following order:
https://github.com/mozilla/pontoon/blob/master/pontoon/sync/vcs/models.py#L54

In the case of Firefox for iOS, `templates` is used and `en-US` is not. As far as Pontoon is concerned, we can safely remove `en-US`. I'm not sure about `templates`, though. It's possible Pontoon will simply jump to using `en-US` instead, but I'd need to test first.

**Comment by flodolo** [comment]
> In the case of Firefox for iOS, templates is used and en-US is not. As far as Pontoon is concerned, we can safely remove en-US. I'm not sure about templates, though. It's possible Pontoon will simply jump to using en-US instead, but I'd need to test first.

Then let's keep the templates folder, its generation is automated and doesn't hurt us.

**Pull request closed without merging**
