### PR TITLE
Added an exception for alerts

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Review by flodolo — APPROVED** [review]

**Comment by flodolo** [comment]
Is there a technical reason of that string not using a placeholder?

**Comment by Delphine** [comment]
Nope. I just thought it would be OK to leave as is in this case (as it sometimes is)
I can revert that though, if it's better to use a placeholder.

**Comment by flodolo** [comment]
Your call. In general, I think the rule of thumb should be "Should this string still say Firefox in a repackaged and rebranded browser?".

**Comment by flodolo** [comment]
(the counter example would be a string like "Firefox Account", where it's always going to be Firefox)

**Comment by Delphine** [comment]
I see what you mean, I understood that in some cases it was just OK to leave as is, if it's not too user facing and part of longer sentences (can't find the doc anymore, but you probably wrote it ;) )
Here it may be better to actually use a placeholder, you're right (and it is a user facing string)... I'll just revert this

**Comment by flodolo** [comment]
> Here it may be better to actually use a placeholder, you're right (and it is a user facing string)... I'll just revert this

It's better to revert after the updated string lands, to avoid constant failure of the linter ;-)

**Comment by Delphine** [comment]
ok! will do it in that order then :)

**Pull request merged**
