### PR TITLE
20200421 9999

### PR DESCRIPTION
**Pull request by garvankeeley**

### CODE REVIEW

**Comment by flodolo** [comment]
CC @gueroJeff 

Can you clarify what's the target version for these strings? We exposed strings and set a deadline on April 27 (in 5 days), adding new strings now if the deadline remains the same doesn't leave enough time.

**Comment by garvankeeley** [comment]
Hi, these strings aren't needed for the v25 release next week, they can be for the release after that.

**Comment by flodolo** [comment]
> Hi, these strings aren't needed for the v25 release next week, they can be for the release after that.

Thanks. Is it OK to wait until April 27 then? Could you point me to a release schedule, to see when the next deadline would be?

**Comment by garvankeeley** [comment]
It is fine to wait yes. Our releases are approx every four weeks, but our schedule is not strict at the moment. Normally I could look at our github releases and add 4 weeks but our schedule is more variable at the moment. Our official release schedule is a on a google calendar which I will try invite you to, that is the best place to look because it has various milestones in our release process like code freeze dates and such.

**Comment by flodolo** [comment]
Thanks, I got the invite to the calendar. Let's leave this one open, although there might be some conflicts by then.

**Pull request merged**
