### PR TITLE
Add new strings for iOS v5.0

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by DineshMv** [comment]
If am not wrong, I think te(telugu) is replaced with `templates: update firefox-ios.xliff`.

**Comment by flodolo** [comment]
@DineshMv 
Telugu has never been included in iOS, templates is the folder used by Pootle as base.

**Comment by flodolo** [comment]
Actually I need to check, there might be a bug on the script :-\

**Comment by flodolo** [comment]
Just to confirm: there is not Telugu in Pootle or Pontoon.

**Comment by DineshMv** [comment]
Ok Sir!

**Pull request merged**
