### PR TITLE
[nl] Translate passcode with toegangscode instead of wachtwoordcode

### PR DESCRIPTION
**Pull request by oeekker**

### CODE REVIEW

**Comment by flodolo** [comment]
Is that the official iOS translation?

CCing also @TonnesM

**Comment by flodolo** [comment]
Answering my own question: yes, 'Toegangscode' is what iOS uses.
https://groups.google.com/d/msg/mozilla.dev.l10n/OBELONPhoqA/HXs3IXNOBwAJ

**Comment by oeekker** [comment]
It is indeed what iOS uses. I've mailed Tonnes about it before submitting the patch, but didn't get a reply from him. I see he just updated the localization to change this?
What's the official way to update translations for nl on github? I see people use Pootle but haven't figured out how to do that and I don't see Tonnes on the contributer list for firefoxios-l10n, so he must be doing it another way too?

**Comment by flodolo** [comment]
It depends on the team: some work on Pootle, some on Pontoon, some directly on GitHub. Besides pinging, there's not much more that I can do.

There's a bug for 2.0 sign-off, eventually you can comment there.

**Comment by unho** [comment]
`nl` language is not being translated at https://mozilla.locamotion.org

**Comment by TonnesM** [comment]
Thanks. This change was included in another one.

https://github.com/mozilla-l10n/firefoxios-l10n/commit/e2ace50d91302b5c57c520b90ac88823b3a4b54a

**Pull request closed without merging**
